/*
    Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef, useState } from "react";

import gsap from "gsap";
import { useGSAP } from "@gsap/react";
import { Float, useGLTF, useTexture, FloatProps } from "@react-three/drei";
import { Mesh } from "three";

const Cube = (props: FloatProps) => {
  const { nodes } = useGLTF("models/cube.glb");

  const texture = useTexture("textures/cube.png");

  const cubeRef = useRef<Mesh>(null);
  const [hovered, setHovered] = useState(false);

  useGSAP(() => {
    if (cubeRef.current?.rotation) {
      gsap
        .timeline({
          repeat: -1,
          repeatDelay: 0.5,
        })
        .to(cubeRef.current.rotation, {
          y: hovered ? "+=2" : `+=${Math.PI * 2}`,
          x: hovered ? "+=2" : `-=${Math.PI * 2}`,
          duration: 2.5,
          stagger: {
            each: 0.15,
          },
        });
    }
  });

  return (
    <Float floatIntensity={2}>
      <group
        position={[9, -4, 0]}
        rotation={[2.6, 0.8, -1.8]}
        scale={0.74}
        dispose={null}
        {...props}
      >
        <mesh
          ref={cubeRef}
          castShadow
          receiveShadow
          // type casting
          geometry={(nodes.Cube as Mesh).geometry}
          material={(nodes.Cube as Mesh).material}
          onPointerEnter={() => setHovered(true)}
        >
          <meshMatcapMaterial matcap={texture} toneMapped={false} />
        </mesh>
      </group>
    </Float>
  );
};

useGLTF.preload("models/cube.glb");

export default Cube;
