/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF, Float, FloatProps } from "@react-three/drei";
import { Mesh } from "three";

const ReactNative3D = (props: FloatProps) => {
  const { nodes, materials } = useGLTF("/models/react-native-logo.glb");

  return (
    <Float floatIntensity={1}>
      <group {...props} dispose={null}>
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Curve001 as Mesh).geometry}
          material={materials["Material.001"]}
          position={[-1.657, -1.656, -0.025]}
          rotation={[1.782, 0, 0.1]}
          scale={24}
        />
      </group>
    </Float>
  );
};

useGLTF.preload("/models/react-native-logo.glb");

export default ReactNative3D;
