/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { Float, FloatProps } from "@react-three/drei";
import { Mesh } from "three";

const Tailwind = (props: FloatProps) => {
  const { nodes, materials } = useGLTF("/models/tailwind.glb");
  return (
    <Float floatIntensity={1}>
      <group {...props} dispose={null}>
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Curve as Mesh).geometry}
          material={materials["SVGMat.004"]}
          position={[2.5, 3, 10]}
          rotation={[1.561, 0, -0.6]}
          scale={125}
        />
      </group>
    </Float>
  );
};

useGLTF.preload("/models/tailwind.glb");

export default Tailwind;
